# Generated by Django 5.1.5 on 2025-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_preferred', models.CharField(max_length=100)),
                ('user_name_first', models.CharField(max_length=100)),
                ('user_name_last', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('user_created_date', models.DateTimeField(auto_now_add=True)),
                ('user_last_logged_in', models.DateTimeField(auto_now_add=True)),
                ('user_is_active', models.BooleanField(default=True)),
                ('user_permissions', models.CharField(max_length=100)),
            ],
        ),
    ]
