# Generated by Django 5.1.5 on 2025-01-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_SISID',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
