# Generated by Django 5.1.5 on 2025-01-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_overview', models.TextField()),
                ('course_duration', models.IntegerField()),
                ('course_image', models.TextField()),
                ('course_slug', models.SlugField(max_length=100)),
                ('course_date', models.DateTimeField(auto_now_add=True)),
                ('course_blueprint', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('module_overview', models.TextField()),
                ('module_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_overview', models.TextField()),
                ('item_type', models.CharField(max_length=50)),
                ('item_id', models.IntegerField()),
                ('item_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('lesson_overview', models.TextField()),
                ('lesson_content', models.TextField()),
                ('lesson_module_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.moduleitem')),
            ],
        ),
    ]
