# Generated by Django 5.1.5 on 2025-01-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_created_date_course_lastest_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
